In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('healthcare_sgx.csv')

In [3]:
df.set_index(['company','year'],inplace=True)

In [4]:
# to see what is all object types for only this line
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  
    print(df.dtypes[df.dtypes=='object'])

Period Ended                                object
Period Length                               object
Source                                      object
Revenue                                     object
Total Revenue                               object
Selling/General/Admin. Expenses, Total      object
Depreciation/Amortisation                   object
Unusual Expense (Income)                    object
Other Operating Expenses, Total             object
Total Operating Expense                     object
Operating Income                            object
Interest Inc.(Exp.),Net-Non-Op., Total      object
Other, Net                                  object
Net Income Before Taxes                     object
Net Income After Taxes                      object
Diluted Weighted Average Shares             object
DPS - Common Stock Primary Issue            object
Period Ended.1                              object
Source.1                                    object
Cash                                        object
Short Term Investments                      object
Cash and Short Term Investments             object
Accounts Receivable - Trade, Net            object
Total Receivables, Net                      object
Prepaid Expenses                            object
Other Current Assets, Total                 object
Total Current Assets                        object
Property/Plant/Equipment, Total - Gross     object
Accumulated Depreciation, Total             object
Property/Plant/Equipment, Total - Net       object
Goodwill, Net                               object
Intangibles, Net                            object
Long Term Investments                       object
Total Assets                                object
Accounts Payable                            object
Accrued Expenses                            object
Notes Payable/Short Term Debt               object
Other Current liabilities, Total            object
Total Current Liabilities                   object
Total Long Term Debt                        object
Total Debt                                  object
Deferred Income Tax                         object
Other Liabilities, Total                    object
Total Liabilities                           object
Common Stock, Total                         object
Retained Earnings (Accumulated Deficit)     object
Treasury Stock - Common                     object
Unrealised Gain (Loss)                      object
Other Equity, Total                         object
Total Equity                                object
Total Liabilities & Shareholders' Equity    object
Total Common Shares Outstanding             object
Period Ended.2                              object
Source.2                                    object
Net Income/Starting Line                    object
Depreciation/Depletion                      object
Non-Cash Items                              object
Cash Taxes Paid                             object
Changes in Working Capital                  object
Cash from Operating Activities              object
Capital Expenditures                        object
Other Investing Cash Flow Items, Total      object
Cash from Investing Activities              object
Total Cash Dividends Paid                   object
Issuance (Retirement) of Stock, Net         object
Cash from Financing Activities              object
Foreign Exchange Effects                    object
Net Change in Cash                          object
Period Ended.3                              object
Return on Assets (ROA)                      object
Return on Equity (ROE)                      object
Operating Margin                            object
Net Profit Margin                           object
Asset Turnover                              object
Debt / Equity                               object
dtype: object

In [5]:
# drop useless row
df.drop([i for i in df.columns if 'Ended' in i]+[i for i in df.columns if 'Source' in i],axis=1,inplace=True)

In [6]:
# change period length
df['Period Length'] = [i.split(' ')[0] for i in df['Period Length']]

In [7]:
df.replace(',','', regex=True, inplace=True)
df = df.apply(pd.to_numeric, errors='coerce')

In [8]:
df.dtypes[df.dtypes=='object']

Series([], dtype: object)

In [11]:
# keeping only ratios
ratios = ['Return on Assets (ROA)','Return on Equity (ROE)','Operating Margin',
                  'Operating Margin','Net Profit Margin','Asset Turnover',
                  'Current Ratio','Quick Ratio','Debt / Equity']

In [12]:
health_ratios = df[ratios]

In [13]:
health_ratios

                    Return on Assets (ROA)  Return on Equity (ROE)  \
company       year
Aoxin Q & M   2015                     NaN                     NaN
              2016                   0.026                   0.026
              2017                   0.020                   0.031
              2018                  -0.002                  -0.002
              2019                  -0.047                  -0.056
...                                    ...                     ...
Yunnan Energy 2015                     NaN                     NaN
              2016                   0.004                   0.012
              2017                   0.077                   0.162
              2018                  -0.010                  -0.017
              2019                  -0.038                  -0.068

                    Operating Margin  Operating Margin  Net Profit Margin  \
company       year
Aoxin Q & M   2015             0.187             0.187              0.103
              2016             0.158             0.158              0.089
              2017             0.084             0.084              0.048
              2018             0.007             0.007             -0.004
              2019            -0.072            -0.072             -0.096
...                              ...               ...                ...
Yunnan Energy 2015             0.029             0.029              0.019
              2016             0.012             0.012              0.003
              2017             0.096             0.096              0.089
              2018            -0.005            -0.005             -0.014
              2019            -0.020            -0.020             -0.064

                    Asset Turnover  Current Ratio  Quick Ratio  Debt / Equity
company       year
Aoxin Q & M   2015             NaN          0.881        0.876            NaN
              2016           0.297          0.639        0.578            NaN
              2017           0.422          3.860        3.615            NaN
              2018           0.446          4.805        4.280          0.004
              2019           0.491          1.767        1.463          0.188
...                            ...            ...          ...            ...
Yunnan Energy 2015             NaN          2.330        1.694          0.480
              2016           1.129          1.840        1.336          0.571
              2017           0.871          1.869        1.306          0.480
              2018           0.694          2.176        1.730          0.089
              2019           0.591         11.066        9.832          0.695

[162 rows x 9 columns]